name: Export Data from Hopsworks

on:
  workflow_dispatch:  # You can trigger it manually from GitHub UI

jobs:
  export-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install hopsworks pandas

    - name: Run export script
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python export_hopsworks_data.py

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: hopsworks-export
        path: hopsworks_data.csv
